title: <p align="center"> Rohan Kale </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/rohan-kale-48243015/">LinkedIn</a>
  <br>   
  I am working as a Senior Technical Lead in Mercedes-Benz R&D on POC topics for the future carlines
  mostly on the interior/exterior comfort features. Been working for 1.5 years in software development
  <br>
  </p>



theme: jekyll-theme-minimal
